// ltt-app/client/components/ChapterDrawer.vue
<template>
  <view class="drawer-mask" v-if="visible" @click="$emit('close')">
    <view class="drawer" :class="{ dark: isDark }" @click.stop>
      <view class="drawer-header" :style="{ paddingTop: (statusBarHeight + 10) + 'px' }">
        <text class="drawer-title">目录</text>
      </view>
      <scroll-view scroll-y class="chapter-list">
        <view v-for="chapter in chapters" :key="chapter.id" class="chapter-group">
          <view
            class="chapter-item"
            :class="{ active: chapter.id === currentChapterId }"
            @click="$emit('select', chapter.id)"
          >
            <text class="chapter-title">{{ chapter.title }}</text>
            <text class="chapter-subtitle" v-if="chapter.subtitle">
              {{ chapter.subtitle }}
            </text>
          </view>
          <!-- 附录子章节 -->
          <view
            v-for="sub in (chapter.subChapters || [])"
            :key="sub.anchor"
            class="chapter-item sub-chapter"
            @click="$emit('select', chapter.id, sub.anchor)"
          >
            <text class="chapter-title">{{ sub.title }}</text>
          </view>
        </view>
      </scroll-view>
    </view>
  </view>
</template>

<script>
export default {
  props: {
    visible: { type: Boolean, default: false },
    chapters: { type: Array, default: () => [] },
    currentChapterId: { type: String, default: '' },
    isDark: { type: Boolean, default: false },
    statusBarHeight: { type: Number, default: 0 },
  },
}
</script>

<style lang="scss" scoped>
.drawer-mask {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.4);
  z-index: 999;
}

.drawer {
  position: absolute;
  top: 0;
  left: 0;
  width: 560rpx;
  height: 100%;
  background: #fff;
  display: flex;
  flex-direction: column;

  &.dark {
    background: #1a1a1a;
    .drawer-title { color: #ffffff; }
    .chapter-item {
      border-bottom-color: #333;
      .chapter-title { color: #f0f0f0; }
      .chapter-subtitle { color: #bbb; }
      &.active {
        background: #2a2a2a;
        .chapter-title { color: #6ba3d6; }
      }
      &.sub-chapter .chapter-title { color: #aaa; }
    }
  }
}

.drawer-header {
  padding: 10px 30rpx 20rpx;
  border-bottom: 1rpx solid #eee;
}

.drawer-title {
  font-size: 34rpx;
  font-weight: bold;
  color: #333;
}

.chapter-list {
  flex: 1;
  height: 0;
}

.chapter-item {
  padding: 24rpx 30rpx;
  border-bottom: 1rpx solid #f0f0f0;
  display: flex;
  flex-direction: column;

  &.active {
    background: #f5f5f5;
    .chapter-title { color: #1a73e8; }
  }
}

.chapter-title {
  font-size: 28rpx;
  color: #333;
  font-weight: 500;
}

.chapter-subtitle {
  font-size: 24rpx;
  color: #999;
  margin-top: 4rpx;
}

.sub-chapter {
  padding-left: 60rpx;
  .chapter-title {
    font-size: 24rpx;
    font-weight: normal;
    color: #666;
  }
}
</style>

// ltt-app-expo/components/ChapterDrawer.tsx
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet, Modal } from 'react-native';
import { Chapter } from '../types/book';

interface ChapterDrawerProps {
  visible: boolean;
  chapters: Chapter[];
  currentChapterId: string;
  isDark: boolean;
  statusBarHeight: number;
  onClose: () => void;
  onSelect: (chapterId: string, anchor?: string) => void;
}

export default function ChapterDrawer({
  visible, chapters, currentChapterId, isDark,
  statusBarHeight, onClose, onSelect,
}: ChapterDrawerProps) {
  const bg = isDark ? '#1a1a1a' : '#fff';
  const titleColor = isDark ? '#fff' : '#333';
  const borderColor = isDark ? '#333' : '#f0f0f0';
  const headerBorder = isDark ? '#333' : '#eee';

  return (
    <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
      <Pressable style={styles.mask} onPress={onClose}>
        <Pressable style={[styles.drawer, { backgroundColor: bg }]} onPress={e => e.stopPropagation()}>
          <View style={[styles.header, {
            paddingTop: statusBarHeight + 10,
            borderBottomColor: headerBorder,
          }]}>
            <Text style={[styles.drawerTitle, { color: titleColor }]}>目录</Text>
          </View>
          <ScrollView style={styles.list}>
            {chapters.map(chapter => (
              <View key={chapter.id}>
                <Pressable
                  style={[
                    styles.item,
                    { borderBottomColor: borderColor },
                    chapter.id === currentChapterId && (isDark ? styles.activeDark : styles.active),
                  ]}
                  onPress={() => onSelect(chapter.id)}
                >
                  <Text style={[
                    styles.chapterTitle,
                    { color: isDark ? '#f0f0f0' : '#333' },
                    chapter.id === currentChapterId && { color: isDark ? '#6ba3d6' : '#1a73e8' },
                  ]}>
                    {chapter.title}
                  </Text>
                  {chapter.subtitle ? (
                    <Text style={[styles.chapterSubtitle, { color: isDark ? '#bbb' : '#999' }]}>
                      {chapter.subtitle}
                    </Text>
                  ) : null}
                </Pressable>
                {chapter.subChapters?.map(sub => (
                  <Pressable
                    key={sub.anchor}
                    style={[styles.item, styles.subItem, { borderBottomColor: borderColor }]}
                    onPress={() => onSelect(chapter.id, sub.anchor)}
                  >
                    <Text style={[styles.subTitle, { color: isDark ? '#aaa' : '#666' }]}>
                      {sub.title}
                    </Text>
                  </Pressable>
                ))}
              </View>
            ))}
          </ScrollView>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

const styles = StyleSheet.create({
  mask: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  drawer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 280,
    height: '100%',
  },
  header: {
    paddingHorizontal: 15,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  drawerTitle: {
    fontSize: 17,
    fontWeight: 'bold',
  },
  list: {
    flex: 1,
  },
  item: {
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  active: {
    backgroundColor: '#f5f5f5',
  },
  activeDark: {
    backgroundColor: '#2a2a2a',
  },
  chapterTitle: {
    fontSize: 14,
    fontWeight: '500',
  },
  chapterSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  subItem: {
    paddingLeft: 30,
  },
  subTitle: {
    fontSize: 12,
    fontWeight: 'normal',
  },
});
