// ltt-app/client/components/ReaderToolbar.vue
<template>
  <view class="toolbar" :class="{ dark: isDark }">
    <view class="toolbar-row">
      <!-- 目录按钮 -->
      <view class="toolbar-btn" @click="$emit('toggleDrawer')">
        <text class="toolbar-icon" :style="{ color: isDark ? '#f0f0f0' : '#333' }">☰</text>
        <text class="btn-label">目录</text>
      </view>

      <!-- 字体缩小 -->
      <view
        class="toolbar-btn"
        :class="{ disabled: fontSize <= fontSizeMin }"
        @click="$emit('decreaseFont')"
      >
        <text class="btn-icon">A-</text>
      </view>

      <!-- 字体大小显示 -->
      <view class="font-size-display">
        <text class="font-size-text">{{ fontSize }}px</text>
      </view>

      <!-- 字体放大 -->
      <view
        class="toolbar-btn"
        :class="{ disabled: fontSize >= fontSizeMax }"
        @click="$emit('increaseFont')"
      >
        <text class="btn-icon">A+</text>
      </view>

      <!-- 深色模式 -->
      <view class="toolbar-btn" @click="$emit('toggleDark')">
        <text class="btn-icon">{{ isDark ? '☀' : '☾' }}</text>
        <text class="btn-label">{{ isDark ? '日间' : '夜间' }}</text>
      </view>
    </view>
  </view>
</template>

<script>
export default {
  props: {
    isDark: { type: Boolean, default: false },
    fontSize: { type: Number, default: 16 },
    fontSizeMin: { type: Number, default: 14 },
    fontSizeMax: { type: Number, default: 24 },
  },
}
</script>

<style lang="scss" scoped>
.toolbar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #fff;
  border-top: 1rpx solid #eee;
  padding-bottom: env(safe-area-inset-bottom);
  z-index: 100;

  &.dark {
    background: #222;
    border-top-color: #333;
    .btn-icon, .btn-label, .font-size-text { color: #f0f0f0; }
    .toolbar-btn.disabled .btn-icon { color: #555; }
  }
}

.toolbar-row {
  display: flex;
  align-items: center;
  justify-content: space-around;
  height: 90rpx;
  padding: 0 20rpx;
}

.toolbar-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 8rpx 16rpx;

  &.disabled {
    opacity: 0.3;
  }
}

.btn-icon {
  font-size: 32rpx;
  color: #333;
}

.toolbar-icon { font-size: 36rpx; }

.btn-label {
  font-size: 20rpx;
  color: #666;
  margin-top: 2rpx;
}

.font-size-display {
  display: flex;
  align-items: center;
  justify-content: center;
}

.font-size-text {
  font-size: 24rpx;
  color: #666;
}
</style>

// ltt-app-expo/components/ReaderToolbar.tsx
import React from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

interface ReaderToolbarProps {
  isDark: boolean;
  fontSize: number;
  fontSizeMin: number;
  fontSizeMax: number;
  onToggleDrawer: () => void;
  onDecreaseFont: () => void;
  onIncreaseFont: () => void;
  onToggleDark: () => void;
}

export default function ReaderToolbar({
  isDark, fontSize, fontSizeMin, fontSizeMax,
  onToggleDrawer, onDecreaseFont, onIncreaseFont, onToggleDark,
}: ReaderToolbarProps) {
  const insets = useSafeAreaInsets();
  const textColor = isDark ? '#f0f0f0' : '#333';
  const labelColor = isDark ? '#f0f0f0' : '#666';
  const bg = isDark ? '#222' : '#fff';
  const border = isDark ? '#333' : '#eee';

  return (
    <View style={[styles.toolbar, {
      backgroundColor: bg,
      borderTopColor: border,
      paddingBottom: insets.bottom,
    }]}>
      <View style={styles.row}>
        <Pressable style={styles.btn} onPress={onToggleDrawer}>
          <Text style={[styles.icon, { color: textColor }]}>☰</Text>
          <Text style={[styles.label, { color: labelColor }]}>目录</Text>
        </Pressable>

        <Pressable
          style={[styles.btn, fontSize <= fontSizeMin && styles.disabled]}
          onPress={onDecreaseFont}
          disabled={fontSize <= fontSizeMin}
        >
          <Text style={[styles.btnIcon, { color: textColor }]}>A-</Text>
        </Pressable>

        <View style={styles.fontDisplay}>
          <Text style={[styles.fontText, { color: labelColor }]}>{fontSize}px</Text>
        </View>

        <Pressable
          style={[styles.btn, fontSize >= fontSizeMax && styles.disabled]}
          onPress={onIncreaseFont}
          disabled={fontSize >= fontSizeMax}
        >
          <Text style={[styles.btnIcon, { color: textColor }]}>A+</Text>
        </Pressable>

        <Pressable style={styles.btn} onPress={onToggleDark}>
          <Text style={[styles.btnIcon, { color: textColor }]}>{isDark ? '☀' : '☾'}</Text>
          <Text style={[styles.label, { color: labelColor }]}>{isDark ? '日间' : '夜间'}</Text>
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  toolbar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopWidth: StyleSheet.hairlineWidth,
    zIndex: 100,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    height: 45,
    paddingHorizontal: 10,
  },
  btn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  disabled: {
    opacity: 0.3,
  },
  icon: {
    fontSize: 18,
  },
  btnIcon: {
    fontSize: 16,
  },
  label: {
    fontSize: 10,
    marginTop: 1,
  },
  fontDisplay: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  fontText: {
    fontSize: 12,
  },
});
